const risks = [
  {id:'martinez',name:'Marisol Martinez',property:'1426 Seabrook Way · Jupiter',risk:'Accepted — payment pending',priority:'critical',owner:'Sam R.',initials:'SR',action:'Call about deposit',due:'37 min overdue',amount:'$18,400',proposal:'PR-1048 · signed 9:12 AM',activity:[['Proposal accepted','9:12 AM','human'],['Deposit link sent','9:13 AM','sync'],['No payment confirmation yet','now','sync']]},
  {id:'li',name:'Evan Li',property:'84 Seagate Drive · Jupiter',risk:'No human attempt',priority:'critical',owner:'You',initials:'JP',action:'Make first contact',due:'3 min left',amount:'$12,600 est.',proposal:'Facebook lead · 2 min ago',activity:[['Lead captured from Facebook','2 min ago','sync'],['Automated acknowledgment sent','2 min ago','sync'],['Awaiting human outreach','now','sync']]},
  {id:'douglas',name:'Heather Douglas',property:'311 Ocean Dunes Rd · Juno',risk:'Appointment cancelled',priority:'high',owner:'Tara M.',initials:'TM',action:'Offer a new time',due:'Due in 18 min',amount:'$9,800 est.',proposal:'Inspection cancelled today',activity:[['Customer cancelled inspection','8:40 AM','sync'],['Recovery message scheduled','8:55 AM','sync'],['No human rebook attempt','now','sync']]},
  {id:'ortiz',name:'Carlos Ortiz',property:'12 Coralberry Ct · Jupiter',risk:'Proposal needs follow-up',priority:'high',owner:'You',initials:'JP',action:'Review open questions',due:'Due today',amount:'$21,300',proposal:'Proposal sent 5 days ago',activity:[['Proposal viewed twice','Yesterday','sync'],['Personal call logged','3 days ago','human'],['No response since','now','sync']]},
  {id:'bennett',name:'Ruth Bennett',property:'708 Loxahatchee Dr · Tequesta',risk:'No-show recovery',priority:'high',owner:'Jared C.',initials:'JC',action:'Rebook inspection',due:'Due today',amount:'$14,100 est.',proposal:'No-show at 10:00 AM',activity:[['Inspection no-show','10:15 AM','sync'],['Automated recovery sent','10:30 AM','sync'],['Awaiting human call','now','sync']]},
  {id:'moore',name:'Diana Moore',property:'19 Atlantic Ave · Palm Beach',risk:'Connected, not booked',priority:'medium',owner:'Sam R.',initials:'SR',action:'Confirm inspection time',due:'Tomorrow',amount:'$16,800 est.',proposal:'Spoke yesterday · no calendar hold',activity:[['Two-way call completed','Yesterday','human'],['Interested in inspection','Yesterday','human'],['No appointment set','now','sync']]}
];
const scenarios={manager:{eyebrow:'BRANCH OPERATIONS',title:'Protect today’s revenue',copy:'Six items need attention in Jupiter. Start with the accepted job waiting on its deposit.',scope:'Jupiter Branch',metrics:['$42,600','92%','7','3 / 4']},sales:{eyebrow:'YOUR WORK',title:'Make the next right move',copy:'Three customers are waiting on you. A human attempt prevents the first SLA breach.',scope:'Jupiter · Sales',metrics:['$34,700','100%','3','—']},corporate:{eyebrow:'CORPORATE PORTFOLIO',title:'See branch risk before it costs revenue',copy:'Jupiter is on target. Miami has two items requiring branch-manager follow-up.',scope:'All branches',metrics:['$88,900','89%','19','3 / 4']}};
let selected='martinez',scenario='manager',logged=[];
const queue=document.querySelector('#queue'),record=document.querySelector('#recordContent'),dialog=document.querySelector('#activityDialog'),toast=document.querySelector('#toast');
function statusClass(priority){return priority==='critical'?'critical':priority==='high'?'high':'medium'}
function riskList(){return risks.filter(r=>!logged.includes(r.id))}
function renderQueue(){const list=riskList();document.querySelector('#queueCount').textContent=list.length;document.querySelector('#navRiskCount').textContent=list.length;queue.innerHTML=list.map((r,i)=>`<button class="risk-row ${selected===r.id?'selected':''}" type="button" data-id="${r.id}" aria-label="Open ${r.name}, ${r.risk}"><div class="risk-customer"><span class="priority ${statusClass(r.priority)}">${i+1}</span><span><span class="customer-name">${r.name}</span><span class="risk-detail">${r.property}</span><span class="status ${statusClass(r.priority)}">${r.risk}</span></span></div><span class="owner"><span class="initials">${r.initials}</span>${r.owner}</span><span class="next-action">${r.action}<small>${r.due}</small></span></button>`).join('');document.querySelector('#emptyState').hidden=list.length>0;const current=list.find(r=>r.id===selected)||list[0];if(current)selected=current.id;renderRecord(current);queue.querySelectorAll('.risk-row').forEach(el=>el.addEventListener('click',()=>{selected=el.dataset.id;renderQueue()}))}
function renderRecord(r){if(!r){record.innerHTML='';return}record.innerHTML=`<div class="record-top"><p class="eyebrow">CUSTOMER & PROPERTY</p><h2 id="recordTitle">${r.name}</h2><p>${r.property}</p><span class="status ${statusClass(r.priority)}">${r.risk}</span></div><section class="record-section"><h3>What matters now</h3><div class="record-grid"><div class="record-field"><span>Potential revenue</span><strong>${r.amount}</strong></div><div class="record-field"><span>Owner</span><strong>${r.owner}</strong></div><div class="record-field"><span>Lifecycle</span><strong>${r.proposal}</strong></div><div class="record-field"><span>Next action</span><strong>${r.action}</strong></div></div></section><section class="record-section"><h3>Activity & sync</h3><div class="activity">${r.activity.map(a=>`<div class="activity-item ${a[2]}">${a[0]}<small>${a[1]}</small></div>`).join('')}</div></section><div class="record-actions"><button class="primary-button" type="button" id="logAttempt">Log a human attempt</button><button class="outline-button" type="button">Open customer record</button></div>`;document.querySelector('#logAttempt').addEventListener('click',()=>{document.querySelector('#dialogContext').textContent=`${r.name} · ${r.property}`;dialog.showModal()})}
function setScenario(next){scenario=next;const s=scenarios[next];document.querySelector('#roleEyebrow').textContent=s.eyebrow;document.querySelector('#title').textContent=s.title;document.querySelector('#introCopy').textContent=s.copy;document.querySelector('#scopeLabel').textContent=s.scope;[...document.querySelectorAll('.metric-strip strong')].forEach((el,i)=>el.textContent=s.metrics[i]);document.querySelectorAll('.scenario').forEach(b=>b.classList.toggle('active',b.dataset.scenario===next));document.querySelector('.corporate-metric').style.display=next==='sales'?'none':'';toastMessage(next==='corporate'?'Portfolio view updated — branch controls remain scoped.':'Scenario updated — mock data only.')}
function toastMessage(message){toast.textContent=message;toast.classList.add('show');window.clearTimeout(window.toastTimer);window.toastTimer=window.setTimeout(()=>toast.classList.remove('show'),3600)}
document.querySelectorAll('.scenario').forEach(button=>button.addEventListener('click',()=>setScenario(button.dataset.scenario)));
document.querySelector('#stateButton').addEventListener('click',()=>{if(riskList().length){logged=[...risks.map(r=>r.id)];renderQueue();toastMessage('Empty state: no urgent revenue risk.')}else{logged=[];selected='martinez';renderQueue();toastMessage('Restored realistic queue state.')}});
document.querySelector('#activityForm').addEventListener('submit',event=>{event.preventDefault();const item=risks.find(r=>r.id===selected);const button=document.querySelector('#saveAttempt');button.textContent='Logging…';button.disabled=true;window.setTimeout(()=>{const outcome=document.querySelector('#attemptOutcome').value;item.activity.unshift([outcome==='connected'?'Two-way conversation logged':'Human outreach attempt logged','just now','human']);if(item.risk==='No human attempt'){logged.push(item.id)}else{item.risk=outcome==='connected'?'Connected — follow-up due':'Attempted — follow-up due';item.priority='medium';item.due='Follow up tomorrow'}dialog.close();button.textContent='Log attempt';button.disabled=false;renderQueue();toastMessage(outcome==='connected'?'Conversation saved and queue updated.':'Attempt saved; SLA status reconciled locally.')},600)});
renderQueue();
